# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               amanfojnr
tagline:             'Learning expands great souls. ~ Namibian proverb'
description:         'I seek to write here what comes on my mind. But you will find patterns if you follow. Say hi to me <a href="https://twitter.com/amanfojnr_" target="_blank">@amanfojnr_</a>.'
url:                 https://amanfojnr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:             
  name:              Amanfo Kenneth Junior
  url:               https://twitter.com/amanfojnr_
  email:             amanfojnr@zoho.com

# Custom vars
version:             1.0.0
